#! /bin/sh

set -ex

srcdir="$(dirname "$0")"
test -z "$srcdir" && srcdir=.

cd "$srcdir"

clone_repo_commit() {
    if test -d "$2/.git"; then
        git -C "$2" reset --hard
        git -C "$2" clean -fd
        if ! git -C "$2" -c advice.detachedHead=false checkout $3; then
            rm -rf "$2"
        fi
    else
        if test -d "$2"; then
            set +x
            echo "error: '$2' is not a Git repository" 1>&2
            exit 1
        fi
    fi
    if ! test -d "$2"; then
        git clone $1 "$2"
        if ! git -C "$2" -c advice.detachedHead=false checkout $3; then
            rm -rf "$2"
            exit 1
        fi
    fi
}

clone_repo_commit \
    https://codeberg.org/osdev/freestnd-c-hdrs.git \
    freestnd-c-hdrs \
    4039f438fb1dc1064d8e98f70e1cf122f91b763b

clone_repo_commit \
    https://codeberg.org/osdev/freestnd-cxx-hdrs.git \
    freestnd-cxx-hdrs \
    85096df5361a4d7ef2ce46947e555ec248c2858e

clone_repo_commit \
    https://codeberg.org/osdev/cc-runtime.git \
    cc-runtime \
    dae79833b57a01b9fd3e359ee31def69f5ae899b

clone_repo_commit \
    https://github.com/limine-bootloader/limine-protocol.git \
    limine-protocol \
    27e81619cc2f82417652d570a32014869803973b

set +x

printf "\nDependencies obtained successfully!\n"
